# Generated by Django 6.0 on 2025-12-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webauthn", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webauthncredential",
            options={
                "verbose_name": "WebAuthn Credential",
                "verbose_name_plural": "WebAuthn Credentials",
            },
        ),
    ]
