# Generated by Django 6.0 on 2025-12-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webauthn", "0002_alter_webauthncredential_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="webauthncredential",
            name="aaguid",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="webauthncredential",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="webauthncredential",
            name="supports_sign_count",
            field=models.BooleanField(default=False),
        ),
    ]
