# Generated by Django 6.0 on 2025-12-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientrecord",
            name="data",
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="encrypted_data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="encrypted_deks",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="record_signature",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="encrypted_encryption_private",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="encryption_public_key",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
