# Generated by Django 6.0 on 2025-12-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_patientrecord_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pending_add_code",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pending_add_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
