# Generated by Django 6.0 on 2026-01-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_pending_add_code_user_pending_add_expiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="encrypted_private_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="private_key_iv",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
