# Generated by Django 6.0 on 2026-01-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_encrypted_private_key_user_private_key_iv"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="certificate",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="xpriv_iv",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
