# Generated by Django 6.0 on 2026-01-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_pendingrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="signing_public_key",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
