# Generated by Django 6.0 on 2026-01-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_signing_public_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="medical_organization",
        ),
        migrations.AddField(
            model_name="user",
            name="encrypted_profile",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="name_hmac",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="org_hmac",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
