# Generated by Django 6.0 on 2026-01-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_user_date_of_birth_remove_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dob_hmac",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
