# Generated by Django 6.0 on 2026-01-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_dob_hmac"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorpatientlink",
            name="encrypted_profile",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
